In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
bn = pd.read_csv('svmfile.csv')

In [3]:
bn.head(20)

age          job   marital            education  default housing loan  \
0    56    housemaid   married             basic.4y       no      no   no   
1    57     services   married          high.school  unknown      no   no   
2    37     services   married          high.school       no     yes   no   
3    40       admin.   married             basic.6y       no      no   no   
4    56     services   married          high.school       no      no  yes   
5    45     services   married             basic.9y  unknown      no   no   
6    59       admin.   married  professional.course       no      no   no   
7    41  blue-collar   married              unknown  unknown      no   no   
8    24   technician    single  professional.course       no     yes   no   
9    25     services    single          high.school       no     yes   no   
10   41  blue-collar   married              unknown  unknown      no   no   
11   25     services    single          high.school       no     yes   no   
12   29  blue-collar    single          high.school       no      no  yes   
13   57    housemaid  divorced             basic.4y       no     yes   no   
14   35  blue-collar   married             basic.6y       no     yes   no   
15   54      retired   married             basic.9y  unknown     yes  yes   
16   35  blue-collar   married             basic.6y       no     yes   no   
17   46  blue-collar   married             basic.6y  unknown     yes  yes   
18   50  blue-collar   married             basic.9y       no     yes  yes   
19   39   management    single             basic.9y  unknown      no   no   

      contact month day_of_week  duration  campaign  pdays  previous  \
0   telephone   may         mon       261         1    999         0   
1   telephone   may         mon       149         1    999         0   
2   telephone   may         mon       226         1    999         0   
3   telephone   may         mon       151         1    999         0   
4   telephone   may         mon       307         1    999         0   
5   telephone   may         mon       198         1    999         0   
6   telephone   may         mon       139         1    999         0   
7   telephone   may         mon       217         1    999         0   
8   telephone   may         mon       380         1    999         0   
9   telephone   may         mon        50         1    999         0   
10  telephone   may         mon        55         1    999         0   
11  telephone   may         mon       222         1    999         0   
12  telephone   may         mon       137         1    999         0   
13  telephone   may         mon       293         1    999         0   
14  telephone   may         mon       146         1    999         0   
15  telephone   may         mon       174         1    999         0   
16  telephone   may         mon       312         1    999         0   
17  telephone   may         mon       440         1    999         0   
18  telephone   may         mon       353         1    999         0   
19  telephone   may         mon       195         1    999         0   

       poutcome  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
0   nonexistent           1.1          93.994          -36.4      4.857   
1   nonexistent           1.1          93.994          -36.4      4.857   
2   nonexistent           1.1          93.994          -36.4      4.857   
3   nonexistent           1.1          93.994          -36.4      4.857   
4   nonexistent           1.1          93.994          -36.4      4.857   
5   nonexistent           1.1          93.994          -36.4      4.857   
6   nonexistent           1.1          93.994          -36.4      4.857   
7   nonexistent           1.1          93.994          -36.4      4.857   
8   nonexistent           1.1          93.994          -36.4      4.857   
9   nonexistent           1.1          93.994          -36.4      4.857   
10  nonexistent           1.1          93.994   

In [4]:
bn.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [5]:
bn.shape

(41188, 21)

In [6]:
bn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()

In [9]:
bn.job.value_counts()

job
admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: count, dtype: int64

In [10]:
bn.job = le.fit_transform(bn.job)

In [11]:
bn.marital.value_counts()

marital
married     24928
single      11568
divorced     4612
unknown        80
Name: count, dtype: int64

In [12]:
bn.marital = le.fit_transform(bn.marital)

In [13]:
bn.education.value_counts()

education
university.degree      12168
high.school             9515
basic.9y                6045
professional.course     5243
basic.4y                4176
basic.6y                2292
unknown                 1731
illiterate                18
Name: count, dtype: int64

In [14]:
bn.education.replace({'unknown':0, 'illiterate':1, 'basic.4y':2, 'basic.6y':3, 'basic.9y':4, 'high.school':5, 'university.degree':6, 'professional.course':7}, inplace=True)

In [15]:
bn.default.value_counts()

default
no         32588
unknown     8597
yes            3
Name: count, dtype: int64

In [16]:
bn.default.replace({'unknown':0, 'no':1, 'yes':2}, inplace=True)

In [17]:
bn.housing.value_counts()

housing
yes        21576
no         18622
unknown      990
Name: count, dtype: int64

In [18]:
bn.housing.replace({'unknown':0, 'no':1, 'yes':2}, inplace=True)

In [19]:
bn.loan.value_counts()

loan
no         33950
yes         6248
unknown      990
Name: count, dtype: int64

In [20]:
bn.loan.replace({'unknown':0, 'no':1, 'yes':2}, inplace=True)

In [21]:
bn.contact.value_counts()

contact
cellular     26144
telephone    15044
Name: count, dtype: int64

In [22]:
bn.contact = le.fit_transform(bn.contact)

In [23]:
bn.month.value_counts()

month
may    13769
jul     7174
aug     6178
jun     5318
nov     4101
apr     2632
oct      718
sep      570
mar      546
dec      182
Name: count, dtype: int64

In [24]:
bn.month.replace({'mar':3, 'apr':4, 'may':5, 'jun':6, 'jul':7, 'aug':8, 'sep':9, 'oct':10, 'nov':11, 'dec':12}, inplace=True)

In [25]:
bn.day_of_week.value_counts()

day_of_week
thu    8623
mon    8514
wed    8134
tue    8090
fri    7827
Name: count, dtype: int64

In [26]:
bn.day_of_week.replace({'mon':1, 'tue':2, 'wed':3, 'thu':4, 'fri':5}, inplace=True)

In [27]:
bn.poutcome.value_counts()

poutcome
nonexistent    35563
failure         4252
success         1373
Name: count, dtype: int64

In [28]:
bn.poutcome.replace({'nonexistent':0, 'failure':1, 'success':2}, inplace=True)

In [29]:
bn.y.value_counts()

y
no     36548
yes     4640
Name: count, dtype: int64

In [30]:
bn.y.replace({'no':0, 'yes':1}, inplace=True)

In [31]:
bn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  int32  
 2   marital         41188 non-null  int32  
 3   education       41188 non-null  int64  
 4   default         41188 non-null  int64  
 5   housing         41188 non-null  int64  
 6   loan            41188 non-null  int64  
 7   contact         41188 non-null  int32  
 8   month           41188 non-null  int64  
 9   day_of_week     41188 non-null  int64  
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  int64  
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [32]:
bn.head()

age  job  marital  education  default  housing  loan  contact  month  \
0   56    3        1          2        1        1     1        1      5   
1   57    7        1          5        0        1     1        1      5   
2   37    7        1          5        1        2     1        1      5   
3   40    0        1          3        1        1     1        1      5   
4   56    7        1          5        1        1     2        1      5   

   day_of_week  duration  campaign  pdays  previous  poutcome  emp.var.rate  \
0            1       261         1    999         0         0           1.1   
1            1       149         1    999         0         0           1.1   
2            1       226         1    999         0         0           1.1   
3            1       151         1    999         0         0           1.1   
4            1       307         1    999         0         0           1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0          93.994          -36.4      4.857       5191.0  0  
1          93.994          -36.4      4.857       5191.0  0  
2          93.994          -36.4      4.857       5191.0  0  
3          93.994          -36.4      4.857       5191.0  0  
4          93.994          -36.4      4.857       5191.0  0

In [33]:
from sklearn.model_selection import train_test_split

In [36]:
bn_train, bn_test = train_test_split(bn, test_size=0.2)

In [60]:
bn_train_y = bn_train.iloc[:,-1]
bn_test_y = bn_test.iloc[:,-1]

In [61]:
bn_train_x = bn_train.iloc[:,:-1] 
bn_test_x = bn_test.iloc[:,:-1]

In [62]:
from sklearn.svm import SVC

In [63]:
svm = SVC(kernel='linear', degree=3)

In [64]:
svm.fit(bn_train_x, bn_train_y)

SVC(kernel='linear')

In [65]:
pred = svm.predict(bn_test_x)
pred

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [66]:
from sklearn.metrics import confusion_matrix

In [67]:
cm = confusion_matrix(bn_test_y, pred)
cm

array([[6588,  713],
       [ 282,  655]], dtype=int64)

In [68]:
#old array
#array([[6863,  438],
#         [ 414,  523]], dtype=int64)

In [69]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [70]:
accuracy_score(bn_test_y, pred)*100

87.92182568584607

In [71]:
precision_score(bn_test_y, pred)*100

47.88011695906433

In [72]:
recall_score(bn_test_y, pred)*100

69.90394877267876

In [54]:
#fpr_new = 

In [53]:
#old accuracy =  89.65
#old hit ratio/precision = 54.42
#old tpr/recall = 55.81
#old fpr = 6

In [73]:
bn_train.shape

(47762, 21)

In [51]:
# bn_train.shape = (32950, 21)  #old shape

In [56]:
df1 = bn_train[bn_train.y == 1]
df1.shape

(3703, 21)

In [57]:
bn_train.y.value_counts()    #old bn_train value_counts

y
0    29247
1     3703
Name: count, dtype: int64

In [ ]:
#oversampling

In [58]:
bn_train = pd.concat([bn_train, df1,df1,df1,df1])

In [59]:
bn_train.y.value_counts()    #new bn_train value_counts

y
0    29247
1    18515
Name: count, dtype: int64

As per the problem statement, our target variable is customer. So in the evaluation scheme, precision becomes the top most priority for our model and then the accuracy, recall score, etc.
It is found that the precision score before oversampling is sufficiently higher than that after oversampling.
So we will choose the model with no oversampling done on it. 